# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 18:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='answer_images/')),
                ('parameter_value_any', models.CharField(default='', max_length=50, null=True)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AttributeAllowedValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('value', models.CharField(max_length=50)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.Attribute')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='object_images/')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectAttributeValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.Attribute')),
                ('attribute_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.AttributeAllowedValue')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.Object')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Parameter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=50)),
                ('type', models.IntegerField(choices=[(0, 'Заранее определенные значения'), (1, 'Число'), (2, 'Строка')], default=0)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParameterAllowedValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('value', models.CharField(max_length=50)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.Parameter')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='question_images/')),
                ('type', models.IntegerField(choices=[(0, 'Заранее определенные значения'), (1, 'Число'), (2, 'Строка')], default=0)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.Parameter')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('data', models.TextField()),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=15)),
                ('current_question_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionAttributeState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('attr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.Attribute')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.Session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionParamState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=50, null=True)),
                ('param', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.Parameter')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.Session')),
            ],
        ),
        migrations.CreateModel(
            name='SessionQuestionState',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.Question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.Session')),
            ],
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='system_images/')),
                ('public', models.BooleanField(default=False)),
                ('slug', models.CharField(default='', max_length=30, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='session',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.System'),
        ),
        migrations.AddField(
            model_name='rule',
            name='system',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expert_app.System'),
        ),
        migrations.AddField(
            model_name='question',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.System'),
        ),
        migrations.AddField(
            model_name='parameter',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.System'),
        ),
        migrations.AddField(
            model_name='object',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.System'),
        ),
        migrations.AddField(
            model_name='attribute',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.System'),
        ),
        migrations.AddField(
            model_name='answer',
            name='parameter_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expert_app.ParameterAllowedValue'),
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_app.Question'),
        ),
    ]
