# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-07 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='object',
            managers=[
                ('objs', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('questions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='system',
            managers=[
                ('systems', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='system',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='system_images/'),
        ),
        migrations.AddField(
            model_name='system',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
