# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-07 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0002_auto_20171007_1447'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='object',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='system',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='system',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
