# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-07 21:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0003_auto_20171007_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='system',
            name='slug',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='system',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
