# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-08 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0008_auto_20171008_1332'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='attribute',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='attributeallowedvalue',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='object',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='objectattributevalue',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='parameter',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='parametervalue',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='rule',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='system',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='system',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rule',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
