# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-08 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0009_auto_20171008_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='object',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='object_images/'),
        ),
    ]
