# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-10-08 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0010_auto_20171008_1809'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ParameterValue',
            new_name='ParameterAllowedValue',
        ),
        migrations.AlterField(
            model_name='parameter',
            name='type',
            field=models.IntegerField(choices=[(0, 'Заранее определенные значения'), (1, 'Число'), (2, 'Строка')], default=0),
        ),
    ]
