# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0014_auto_20171009_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionparamstate',
            name='value_any',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
