# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-10 13:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_app', '0015_sessionparamstate_value_any'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sessionparamstate',
            name='value_any',
        ),
    ]
